'use client';
import { useEffect, useState } from 'react';
import { BarChart3 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, CartesianGrid } from 'recharts';

export default function Analytics(){const s=createClient();const [tasks,setTasks]=useState<any[]>([]);const [logs,setLogs]=useState<any[]>([]);const [goals,setGoals]=useState<any[]>([]);const [twin,setTwin]=useState<any>();
useEffect(()=>{(async()=>{const [{data:t},{data:l},{data:g},{data:tw}]=await Promise.all([s.from('tasks').select('status,estimated_hours,created_at'),s.from('habit_logs').select('date,completed,value').order('date'),s.from('goals').select('title,progress'),s.from('twin_profiles').select('*').maybeSingle()]);setTasks(t||[]);setLogs(l||[]);setGoals(g||[]);setTwin(tw)})()},[]);
const completion=tasks.length?Math.round(tasks.filter(x=>x.status==='done').length/tasks.length*100):0;const workload=tasks.reduce((a,x)=>a+Number(x.estimated_hours||0),0);const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const k=d.toISOString().slice(0,10);return {day:d.toLocaleDateString(undefined,{weekday:'short'}),completed:logs.filter(x=>x.date===k&&x.completed).length}});
return <div><div className="mb-8"><div className="flex items-center gap-3"><BarChart3 className="text-violet-300"/><h1 className="text-3xl font-black">Analytics</h1></div><p className="muted mt-1">Real metrics calculated from your Supabase data.</p></div><div className="grid gap-4 md:grid-cols-4"><Metric label="Task completion" value={`${completion}%`}/><Metric label="Unfinished workload" value={`${workload.toFixed(1)}h`}/><Metric label="Active goals" value={String(goals.length)}/><Metric label="Daily capacity" value={`${Number(twin?.available_hours||0).toFixed(1)}h`}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="glass card"><h2 className="font-bold">Habit activity — last 7 days</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={days}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.08)"/><XAxis dataKey="day" stroke="#888"/><YAxis allowDecimals={false} stroke="#888"/><Tooltip/><Bar dataKey="completed" fill="#8b5cf6" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="glass card"><h2 className="font-bold">Goal progress</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={goals.map(g=>({name:g.title.slice(0,14),progress:Number(g.progress||0)}))}><CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,.08)"/><XAxis dataKey="name" stroke="#888"/><YAxis domain={[0,100]} stroke="#888"/><Tooltip/><Line type="monotone" dataKey="progress" stroke="#22d3ee" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="glass card"><div className="muted text-sm">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
