'use client';
import { useEffect, useState } from 'react';
import { Brain, Plus, Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Memory={id:string;category:string;content:string;source:string|null;confidence:number;created_at:string};
export default function Memory(){const s=createClient();const [items,setItems]=useState<Memory[]>([]);const [open,setOpen]=useState(false);const [category,setCategory]=useState('preference');const [content,setContent]=useState('');const [source,setSource]=useState('user');
async function load(){const {data}=await s.from('memories').select('*').order('updated_at',{ascending:false});setItems(data||[])} useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();const {data:{user}}=await s.auth.getUser();if(!user)return;await s.from('memories').insert({user_id:user.id,category,content,source,confidence:1});setContent('');setOpen(false);load()}
async function remove(id:string){await s.from('memories').delete().eq('id',id);load()}
return <div><div className="mb-8 flex items-end justify-between"><div><div className="flex items-center gap-3"><Brain className="text-violet-300"/><h1 className="text-3xl font-black">Memory</h1></div><p className="muted mt-1">Facts and preferences you explicitly allow Hamiq to retain.</p></div><button onClick={()=>setOpen(!open)} className="btn btn-primary gap-2"><Plus size={17}/> Add memory</button></div>{open&&<form onSubmit={add} className="glass card mb-5 grid gap-3 md:grid-cols-3"><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option>preference</option><option>goal</option><option>constraint</option><option>project</option><option>important_fact</option></select><input className="input" value={source} onChange={e=>setSource(e.target.value)} placeholder="Source"/><textarea required className="input md:col-span-3" value={content} onChange={e=>setContent(e.target.value)} placeholder="What should Hamiq remember?"/><button className="btn btn-primary md:col-span-3">Save memory</button></form>}<div className="space-y-3">{items.map(x=><div className="glass card" key={x.id}><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-violet-500/10 px-3 py-1 text-xs text-violet-200">{x.category}</span><p className="mt-3 font-medium">{x.content}</p><p className="muted mt-2 text-xs">Source: {x.source||'user'} · Confidence: {Math.round(Number(x.confidence||0)*100)}%</p></div><button onClick={()=>remove(x.id)} className="text-red-300"><Trash2 size={16}/></button></div></div>)}{!items.length&&<div className="glass card muted">No memories yet. Hamiq will not silently create permanent memories from ambiguous input.</div>}</div></div>}
