'use client';
import { useEffect, useState } from 'react';
import { Check, Plus, Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Habit={id:string;name:string;frequency:string;target:number};
type Log={habit_id:string;date:string;completed:boolean;value:number};
function today(){return new Date().toISOString().slice(0,10)}
export default function Habits(){const s=createClient();const [habits,setHabits]=useState<Habit[]>([]);const [logs,setLogs]=useState<Log[]>([]);const [name,setName]=useState('');const [frequency,setFrequency]=useState('daily');const [target,setTarget]=useState('1');const [open,setOpen]=useState(false);
async function load(){const [{data:h},{data:l}]=await Promise.all([s.from('habits').select('*').order('created_at'),s.from('habit_logs').select('*').gte('date',new Date(Date.now()-6*86400000).toISOString().slice(0,10)).lte('date',today())]);setHabits(h||[]);setLogs(l||[])}
useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();const {data:{user}}=await s.auth.getUser();if(!user)return;await s.from('habits').insert({user_id:user.id,name,frequency,target:Number(target)});setName('');setOpen(false);load()}
async function toggle(h:Habit){const existing=logs.find(x=>x.habit_id===h.id&&x.date===today());if(existing){await s.from('habit_logs').delete().eq('id',(existing as any).id)}else{const {data:{user}}=await s.auth.getUser();if(!user)return;await s.from('habit_logs').insert({habit_id:h.id,user_id:user.id,date:today(),value:1,completed:true})}load()}
async function remove(id:string){await s.from('habits').delete().eq('id',id);load()}
return <div><div className="mb-8 flex items-end justify-between"><div><h1 className="text-3xl font-black">Habits</h1><p className="muted mt-1">Track real habits and feed consistency into your Hamix.</p></div><button onClick={()=>setOpen(!open)} className="btn btn-primary gap-2"><Plus size={17}/> New habit</button></div>{open&&<form onSubmit={add} className="glass card mb-5 grid gap-3 md:grid-cols-4"><input required className="input md:col-span-2" placeholder="e.g. Study 2 hours" value={name} onChange={e=>setName(e.target.value)}/><select className="input" value={frequency} onChange={e=>setFrequency(e.target.value)}><option>daily</option><option>weekly</option></select><input className="input" type="number" min="1" value={target} onChange={e=>setTarget(e.target.value)}/><button className="btn btn-primary md:col-span-4">Save habit</button></form>}<div className="grid gap-4 md:grid-cols-2">{habits.map(h=>{const done=logs.some(x=>x.habit_id===h.id&&x.date===today()&&x.completed);const last7=logs.filter(x=>x.habit_id===h.id&&x.completed).length;return <div className="glass card" key={h.id}><div className="flex items-start justify-between"><div><h2 className="font-bold">{h.name}</h2><p className="muted mt-1 text-sm">{h.frequency} · target {h.target}</p></div><button onClick={()=>remove(h.id)} className="text-red-300"><Trash2 size={16}/></button></div><div className="mt-5 flex items-center justify-between"><div><div className="text-2xl font-black">{last7}</div><div className="muted text-xs">logged in last 7 days</div></div><button onClick={()=>toggle(h)} className={`btn gap-2 ${done?'bg-cyan-500/15 text-cyan-200':''}`}><Check size={16}/>{done?'Done today':'Mark today'}</button></div></div>})}{!habits.length&&<div className="glass card muted md:col-span-2">No habits yet. Add sleep, study, exercise, reading, or any custom habit.</div>}</div></div>}
