import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function GET(){
  const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});
  const [{data:tasks},{data:twin},{data:classes},{data:events},{data:profile}]=await Promise.all([
    s.from('tasks').select('id,title,status,priority,progress,estimated_hours,deadline,category').neq('status','done').order('deadline',{ascending:true,nullsFirst:false}),
    s.from('twin_profiles').select('available_hours,study_hours,sleep_hours').eq('user_id',user.id).maybeSingle(),
    s.from('class_timetable').select('course_name,start_time,end_time,day_of_week').eq('user_id',user.id),
    s.from('events').select('title,start_time,end_time').eq('user_id',user.id).gte('start_time',new Date().toISOString()).order('start_time').limit(20),
    s.from('profiles').select('timezone').eq('id',user.id).maybeSingle()
  ]);
  const now=new Date(); const tz=profile?.timezone||'Asia/Karachi';
  const weekdayName=new Intl.DateTimeFormat('en-US',{timeZone:tz,weekday:'long'}).format(now); const weekdayMap:any={Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6,Sunday:7}; const weekday=weekdayMap[weekdayName]||1; const nowParts=new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now); const nowHour=Number(nowParts.find(x=>x.type==='hour')?.value||0)%24; const nowMinute=Number(nowParts.find(x=>x.type==='minute')?.value||0); const currentMinutes=nowHour*60+nowMinute;
  const ranked=(tasks||[]).map((t:any)=>{const due=t.deadline?new Date(t.deadline).getTime():Infinity;const days=due===Infinity?99:Math.max(0,(due-now.getTime())/86400000);const urgency=days<1?5:days<2?4:days<4?3:1;const priority=t.priority==='high'?3:t.priority==='medium'?2:1;const incomplete=1-(Number(t.progress||0)/100);const score=urgency*4+priority*2+incomplete+Math.min(3,Number(t.estimated_hours||1)/2);return {...t,score}}).sort((a,b)=>b.score-a.score).slice(0,5);
  const todayClasses=(classes||[]).filter((x:any)=>x.day_of_week===weekday).map((x:any)=>({title:x.course_name,start:x.start_time.slice(0,5),end:x.end_time.slice(0,5),type:'class'})); const eventBlocks=(events||[]).filter((e:any)=>new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(e.start_time))===new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(now)).map((e:any)=>{const a=new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(e.start_time));const b=new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(e.end_time));return {start:(Number(a.find(x=>x.type==='hour')?.value||0)%24)*60+Number(a.find(x=>x.type==='minute')?.value||0),end:(Number(b.find(x=>x.type==='hour')?.value||0)%24)*60+Number(b.find(x=>x.type==='minute')?.value||0),title:e.title};}); const classBlocks=todayClasses.map((x:any)=>{const [sh,sm]=x.start.split(':').map(Number);const [eh,em]=x.end.split(':').map(Number);return {start:sh*60+sm,end:eh*60+em,title:x.title};}); const blocks=[...classBlocks,...eventBlocks].sort((a,b)=>a.start-b.start); const freeWindows:any[]=[]; let cursor=Math.max(8*60,currentMinutes); for(const b of blocks){if(b.end<=cursor)continue; if(b.start>cursor){freeWindows.push({start:cursor,end:Math.min(b.start,22*60)});} cursor=Math.max(cursor,b.end); if(cursor>=22*60)break;} if(cursor<22*60)freeWindows.push({start:cursor,end:22*60}); const fmt=(m:number)=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`; const usableWindows=freeWindows.filter((w:any)=>w.end-w.start>=30).map((w:any)=>({start:fmt(w.start),end:fmt(w.end),minutes:w.end-w.start}));
  return NextResponse.json({tasks:ranked,todayClasses,freeWindows:usableWindows,events:events||[],twin:twin||{},timezone:tz,message:ranked[0]?`Your next focus should be ${ranked[0].title}. It has the highest combination of urgency, priority, and remaining work.`:'You have no unfinished tasks. Use your free time for a goal, habit, or rest.'});
}
