'use client';
import { useEffect, useState } from 'react';
import { CheckCircle2, Plus, Trash2, Pencil, Bell, X, Save } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Task = { id:string; title:string; description?:string; status:string; priority:string; estimated_hours:number; actual_hours?:number; deadline?:string|null; reminder_at?:string|null; progress?:number; category?:string|null; };
const blank = { title:'', description:'', hours:'1', actualHours:'0', priority:'medium', deadline:'', reminderAt:'', progress:'0', category:'' };

export default function Tasks(){
  const [tasks,setTasks]=useState<Task[]>([]); const [form,setForm]=useState(blank); const [editing,setEditing]=useState<Task|null>(null); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const s=createClient();
  async function load(){const {data,error}=await s.from('tasks').select('*').order('deadline',{ascending:true,nullsFirst:false}); if(!error)setTasks((data||[]) as Task[]); setLoading(false)}
  useEffect(()=>{load()},[]);
  function openNew(){setEditing(null);setForm(blank);setOpen(true)}
  function openEdit(t:Task){setEditing(t);setForm({title:t.title,description:t.description||'',hours:String(t.estimated_hours??1),actualHours:String(t.actual_hours??0),priority:t.priority||'medium',deadline:t.deadline?toLocal(t.deadline):'',reminderAt:t.reminder_at?toLocal(t.reminder_at):'',progress:String(t.progress??(t.status==='done'?100:0)),category:t.category||''});setOpen(true)}
  function toLocal(value:string){const d=new Date(value);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
  async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const {data:{user}}=await s.auth.getUser();if(!user){setSaving(false);return}const progress=Math.max(0,Math.min(100,Number(form.progress)||0));const payload={title:form.title.trim(),description:form.description||null,estimated_hours:Number(form.hours)||1,actual_hours:Number(form.actualHours)||0,priority:form.priority,deadline:form.deadline?new Date(form.deadline).toISOString():null,reminder_at:form.reminderAt?new Date(form.reminderAt).toISOString():null,progress,category:form.category||null,status:progress>=100?'done':'todo',completed_at:progress>=100?new Date().toISOString():null,user_id:user.id};const q=editing?s.from('tasks').update(payload).eq('id',editing.id):s.from('tasks').insert(payload);const {error}=await q;if(!error){setOpen(false);await load()}setSaving(false)}
  async function toggle(t:Task){const done=t.status!=='done';await s.from('tasks').update({status:done?'done':'todo',progress:done?100:Math.min(99,Number(t.progress||0)),completed_at:done?new Date().toISOString():null}).eq('id',t.id);load()}
  async function remove(id:string){if(confirm('Delete this task?')){await s.from('tasks').delete().eq('id',id);load()}}
  async function enableNotifications(){if('Notification' in window){const p=await Notification.requestPermission(); if(p==='granted') alert('Task reminders are enabled while Hamix is open in this browser.')}}
  return <div>
    <div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-black">Tasks</h1><p className="muted mt-1">Edit, complete, track progress, and set reminders for your real tasks.</p></div><div className="flex gap-2"><button onClick={enableNotifications} className="btn btn-ghost gap-2"><Bell size={16}/> Enable reminders</button><button onClick={openNew} className="btn btn-primary gap-2"><Plus size={17}/> New Task</button></div></div>
    {open&&<form onSubmit={save} className="glass card mb-5 grid gap-3 md:grid-cols-4"><div className="md:col-span-4 flex items-center justify-between"><h2 className="font-bold">{editing?'Edit task':'Create task'}</h2><button type="button" onClick={()=>setOpen(false)} className="muted"><X size={18}/></button></div><input required className="input md:col-span-2" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Task title"/><input className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category / course"/><select className="input" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select><textarea className="input md:col-span-4 min-h-20" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description / notes"/><label className="text-sm muted">Estimated hours<input className="input mt-1" type="number" min="0.25" step="0.25" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></label><label className="text-sm muted">Actual hours<input className="input mt-1" type="number" min="0" step="0.25" value={form.actualHours} onChange={e=>setForm({...form,actualHours:e.target.value})}/></label><label className="text-sm muted">Progress %<input className="input mt-1" type="number" min="0" max="100" value={form.progress} onChange={e=>setForm({...form,progress:e.target.value})}/></label><label className="text-sm muted">Deadline<input className="input mt-1" type="datetime-local" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label><label className="text-sm muted md:col-span-2">Remind me at<input className="input mt-1" type="datetime-local" value={form.reminderAt} onChange={e=>setForm({...form,reminderAt:e.target.value})}/></label><button disabled={saving} className="btn btn-primary md:col-span-2 gap-2"><Save size={16}/>{saving?'Saving...':editing?'Update Task':'Save to Hamix'}</button></form>}
    {loading?<p className="muted">Loading...</p>:<div className="space-y-3">{tasks.length?tasks.map(t=><div className="glass card" key={t.id}><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 gap-3"><button onClick={()=>toggle(t)} aria-label="toggle"><CheckCircle2 className={t.status==='done'?'text-cyan-300':'text-gray-600'}/></button><div className="min-w-0"><div className={`font-bold ${t.status==='done'?'line-through opacity-60':''}`}>{t.title}</div><div className="muted mt-1 text-sm">{t.deadline?`Due ${new Date(t.deadline).toLocaleString()}`:'No deadline'} · {t.estimated_hours}h estimated · {Number(t.progress||0)}% complete</div>{t.reminder_at&&<div className="mt-1 flex items-center gap-1 text-xs text-violet-300"><Bell size={12}/>Reminder {new Date(t.reminder_at).toLocaleString()}</div>}<div className="mt-2 h-2 max-w-xl overflow-hidden rounded-full bg-white/10"><div className="h-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:`${Math.max(0,Math.min(100,Number(t.progress||0)))}%`}}/></div></div></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white/5 px-3 py-1">{t.priority}</span><button onClick={()=>openEdit(t)} className="rounded-full bg-violet-500/10 px-3 py-1 text-violet-200 flex items-center gap-1"><Pencil size={13}/> Edit</button><button onClick={()=>remove(t.id)} className="rounded-full bg-red-500/10 px-3 py-1 text-red-300"><Trash2 size={14}/></button></div></div></div>):<div className="glass card muted">No tasks yet. Add your actual university, work, or personal tasks.</div>}</div>}
    <p className="muted mt-5 text-xs">Browser reminders require notification permission and the Hamix tab to be open. For reminders when the app is completely closed, add Web Push/cron in the production deployment.</p>
  </div>
}
