'use client';
import {useEffect,useMemo,useState} from 'react';
import {FileText,Printer,Sparkles,RefreshCw} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import AIRichText from '@/app/components_ai_rich_text';

type ReportData={tasks:any[];goals:any[];habits:any[];logs:any[];events:any[];twin:any};
export default function Reports(){const s=createClient();const [d,setD]=useState<ReportData>({tasks:[],goals:[],habits:[],logs:[],events:[],twin:null});const [loading,setLoading]=useState(true);const [ai,setAi]=useState('');const [aiLoading,setAiLoading]=useState(false);
async function load(){setLoading(true);const [{data:tasks},{data:goals},{data:habits},{data:logs},{data:events},{data:twin}]=await Promise.all([s.from('tasks').select('*').order('deadline'),s.from('goals').select('*').order('target_date'),s.from('habits').select('*'),s.from('habit_logs').select('*').order('date',{ascending:false}).limit(100),s.from('events').select('*').order('start_time'),s.from('twin_profiles').select('*').maybeSingle()]);setD({tasks:tasks||[],goals:goals||[],habits:habits||[],logs:logs||[],events:events||[],twin});setLoading(false)}
useEffect(()=>{load()},[]);
const stats=useMemo(()=>{const total=d.tasks.length,done=d.tasks.filter(x=>x.status==='done').length;const estimated=d.tasks.reduce((a,x)=>a+Number(x.estimated_hours||0),0);const actual=d.tasks.reduce((a,x)=>a+Number(x.actual_hours||0),0);const avgGoal=d.goals.length?d.goals.reduce((a,x)=>a+Number(x.progress||0),0)/d.goals.length:0;return {total,done,completion:total?Math.round(done/total*100):0,estimated,actual,avgGoal}},[d]);
async function generateAI(){setAiLoading(true);setAi('');try{const r=await fetch('/api/ai/insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reportType:'progress_report',generatedAt:new Date().toISOString(),stats,twin:d.twin,goals:d.goals.map(x=>({title:x.title,progress:x.progress,target_date:x.target_date})),tasks:d.tasks.map(x=>({title:x.title,status:x.status,progress:x.progress,priority:x.priority,estimated_hours:x.estimated_hours,actual_hours:x.actual_hours,deadline:x.deadline}))})});const j=await r.json();setAi(j.insight||j.error||'No AI report generated.')}catch(e){setAi('AI report could not be generated.')}finally{setAiLoading(false)}}
if(loading)return <p className="muted">Generating your live report...</p>;
return <div className="printable"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3"><FileText className="text-violet-300"/><h1 className="text-3xl font-black">Progress Reports</h1></div><p className="muted mt-1">Generate a fresh report from your current Supabase data whenever you want.</p></div><div className="no-print flex gap-2"><button onClick={load} className="btn btn-ghost gap-2"><RefreshCw size={16}/> Refresh</button><button onClick={generateAI} disabled={aiLoading} className="btn btn-ghost gap-2"><Sparkles size={16}/>{aiLoading?'Writing...':'AI Summary'}</button><button onClick={()=>window.print()} className="btn btn-primary gap-2"><Printer size={16}/> Print / Save PDF</button></div></div>
<div className="glass card"><div className="text-sm muted">Generated</div><div className="mt-1 font-bold">{new Date().toLocaleString()}</div></div>
<div className="mt-5 grid gap-4 md:grid-cols-4"><Metric label="Task completion" value={`${stats.completion}%`}/><Metric label="Tasks completed" value={`${stats.done}/${stats.total}`}/><Metric label="Estimated workload" value={`${stats.estimated.toFixed(1)}h`}/><Metric label="Average goal progress" value={`${Math.round(stats.avgGoal)}%`}/></div>
<div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="glass card"><h2 className="font-bold text-lg">Goals</h2><div className="mt-4 space-y-4">{d.goals.length?d.goals.map(g=><div key={g.id}><div className="flex justify-between text-sm"><span>{g.title}</span><span>{Number(g.progress||0)}%</span></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:`${Math.max(0,Math.min(100,Number(g.progress||0)))}%`}}/></div></div>):<p className="muted">No goals yet.</p>}</div></section><section className="glass card"><h2 className="font-bold text-lg">Tasks</h2><div className="mt-4 space-y-2">{d.tasks.slice(0,10).map(t=><div key={t.id} className="flex items-center justify-between rounded-xl bg-white/5 p-3"><span className={t.status==='done'?'line-through opacity-60':''}>{t.title}</span><span className="text-sm text-violet-200">{Number(t.progress||0)}%</span></div>)}{!d.tasks.length&&<p className="muted">No tasks yet.</p>}</div></section></div>
<section className="glass card mt-5"><h2 className="font-bold text-lg">Habits & activity</h2><p className="muted mt-2">{d.habits.length} habits configured · {d.logs.filter(x=>x.completed).length} completed logs recorded.</p></section>
{ai&&<section className="glass card mt-5"><div className="flex items-center gap-2 font-bold"><Sparkles size={17} className="text-violet-300"/>AI report summary</div><div className="mt-4 rounded-2xl border border-[#eadfce] bg-[#fffdf9] p-4 sm:p-5"><AIRichText text={ai} /></div></section>}
<p className="muted no-print mt-5 text-xs">This report describes your current recorded data. It does not predict your future.</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="glass card"><div className="muted text-sm">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
